ToothlessGear/node-gcm

- README.md
It popped up when I copy/pasted, so I thought id do a quick fix :)
> removed extra whitespace in readme example

- lib/sender.js
Sometimes you'll want to just send something, and not care if it succeeds. That will now be possible.
The following will no longer throw an exception:
```javascript
sender.sendNoRetry(message, registrationIds);
sender.send(message, registrationIds, 4);
```
> Make the callbacks for Sender#{send,sendNoRetry} optional

- README.md
- lib/message.js
- test/unit/messageSpec.js
This PR makes `addData` work as `addDataWithKeyValue` or `addDataWithObject` depending on the number of arguments given.
This results in cleaner syntax if people insist on using `addData*` (instead of setting all values at time of construction).
> Multi-purpose addData

- lib/message.js
Fixes #88 
Hold on to this until `v0.10` -- it's too big of a change for a patch version.
> Deprecate add data with

- package.json
This removes the deprecation warning when running tests.
`chai` and `mocha` are the only changes that actually brings in another version. The other deps were installing latest.
> "request" can be updated from ^2.27.0 to ^2.55.0 (Installed: 2.55.0, Latest: 2.55.0)
"debug" can be updated from ^0.8.1 to ^2.1.3 (Installed: 0.8.1, Latest: 2.1.3)
"chai" can be updated from ^1.9.1 to ^2.2.0 (Installed: 1.10.0, Latest: 2.2.0)
"mocha" can be updated from ^1.21.0 to ^2.2.4 (Installed: 1.21.5, Latest: 2.2.4)
"proxyquire" can be updated from ^1.0.1 to ^1.4.0 (Installed: 1.4.0, Latest: 1.4.0)
"sinon" can be updated from ^1.10.3 to ^1.14.1 (Installed: 1.14.1, Latest: 1.14.1)
> Bump devDependencies

- lib/sender.js
- test/unit/senderSpec.js
> prevent recursion when errors are thrown in `send()` callback

- lib/constants.js
- lib/message-options.js
- lib/message.js
- lib/sender.js
- test/unit/messageSpec.js
- test/unit/senderSpec.js
The primary purpose of this PR is to move the responsibility for serializing from *our* abstract representations of Messages to the raw JSON to the `Message`. Previously, this responsibility was in `Sender`, which made extending the set of supported parameters very hard.
This PR also changes most tests so they no longer depend on internal state of `Message`.
The outwards interfaces are unchanged.
I will leave this PR open to comments for 24 hours before merging (until 2015-07-13 15:00 Europe/Copenhagen).
> Delegate responsibility of serialization to Message

- CHANGELOG.md
- README.md
- lib/message-options.js
- lib/sender.js
- test/unit/messageSpec.js
- test/unit/senderSpec.js
This PR adds support for the last few parameters that we did not yet support (fixes #136, fixes #101):
- priority
- content_available (we call it contentAvailable)
- restricted_package_name (we call it restrictedPackageName)
Additionally this PR changes the internal workings of Sender, so if only a single registration id is given, it will go into the `to` field. Fixes #107. Fixes #134.
This allows for use-cases such as Topic Messaging and Group Messaging (mentioned in #134).
> Update to support new params in gcm

- README.md
- lib/message-options.js
- package.json
- test/unit/messageSpec.js
According to [GCM documentation](https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message), priority can be set using a string of `normal` or `high` instead of a number.
Fixes #147
> Properly support priority

- README.md
- lib/sender.js
- package.json
- test/unit/senderSpec.js
Following issue #146:
This is a quick fix for sending to a topic with `send()`:
```javascript
sender.send(
message,
{ topic: '/topics/global' }, // can also be { registrationIds: [...] },
{ retries: 2 },
callback
);
```
If it looks good enough, I'll add support for the same parameters for `sendNoRetry()`.
> Support explicit topic target in send()

- lib/sender.js
`util.isArray()` just got deprecated and is effectively the same as
`Array.isArray()`.
https://github.com/nodejs/node/blob/master/lib/util.js#L598
http://stackoverflow.com/a/22848148/88851
> Replace util.isArray() with Array.isArray()

- lib/constants.js
- package.json
Google has modified the GCM documentation to use a new URL for its HTTP GCM endpoint: https://developers.google.com/cloud-messaging/http
* Closes #162
> Update the hostname of the GCM endpoint

- README.md
Update the README.md, modifying the project description to exclude Android (as GCM now supports both Android and iOS devices), and remove the C2DM reference -- it's outdated.
Closes #166.
> Update README.md with generalized project description

- CHANGELOG.md
- examples/notification.js
- lib/sender.js
- test/unit/senderSpec.js
Create an alias for `registrationTokens` as per the new GCM terminology "registration tokens" instead of "registration IDs". 
```
// Now the sender can be used to send messages
sender.send(message, { registrationTokens: regTokens }, function (err, result) {
if(err) console.error(err);
else    console.log(result);
});
```
It behaves the same as `registrationIds`. We decided to leave `registrationIds` intact to maintain backward compatibility.
Also, update the "no recipient" error message, as recipients can be both tokens and topics now.
```
if (Array.isArray(recipient) && !recipient.length) {
debug('No recipient provided!');
return process.nextTick(callback.bind(this, 'No recipient provided!', null));
}
```
Finally, incorporate the new alias in the senderSpec.js test.
References #160.
> Add registrationTokens alias (as per new GCM terminology)

- README.md
Use the new `registrationTokens` alias and update the terminology to reference recipient devices as "registration tokens" instead of "registration IDs", as per the updated GCM documentation.
References #160 and depends on PR #169 (for the `registrationTokens` alias)
> Update README.md with registrationTokens terminology and alias

- README.md
- examples/notification.js
- lib/sender.js
- test/unit/senderSpec.js
As per the outcome of #104, we decided to rename the `result` parameter
to `response` in all sender.send() and sender.sendNoRetry() calls.
Files renamed:
* README.md usages of sender.send/sendNoRetry
* examples/notification.js usage of sender.send
* senderSpec.js tests utilizing sender.send/sendNoRetry
* lib/sender.js references to the old parameter in both
sender.sendNoRetry and in other declarations
Ran `npm test` and success returned.
> Rename send/sendNoRetry callback param to "response"

- README.md
- lib/sender.js
- package.json
- test/unit/senderSpec.js
As discussed in #179, we'd like developers to be able to set all request options externally, by providing an object to the `gcm.Sender()` constructor, such as the request proxy, timeout, strictSSL, etc.
Changes:
* Require `lodash`
* Removed manual checks for `proxy`, `maxSockets`, `timeout`, and
`strictSSL` request options
* Added a variable `sender_options` that contains the request options passed to gcm.Sender()
* Added a variable `request_options` which uses Lodash's `_.defaults()` function to prevent overriding our internal options with
externally-provided ones
* Allow overriding `timeout` externally if provided, if not, use `Constants.SOCKET_TIMEOUT` (same as old behavior)
* Modified `post_req` to use the `request_options` instead of the old `post_options` which was manually …
> Allow setting all request options

- lib/sender.js
- test/unit/senderSpec.js
As per @alemonmk's suggestion in #187, when supplying a single registration token inside an array, we should set the `to` property and not the `registration_ids` property, so that the push notification will be sent as a unicast message, which is encouraged by the [GCM documentation](https://developers.google.com/cloud-messaging/http-server-ref#table1).
To achieve this, I added a check for a single-element array inside `sendNoRetry`.
The response from the GCM server is identical for unicast and multicast messages.
Also, added the following tests to check for correct utilization of the `to` GCM request property:
* Should set the to field if a single reg token is passed inside the recipient array
* Should set the to field if a single reg token is passed inside the registrationTokens array
* …
> Improved support for unicast messaging (sending to one device)

- lib/sender.js
- test/unit/senderSpec.js
This PR closes #97, an issue regarding specifying a custom `proxy` for node-gcm requests.
Due to a bug with the `request` module (explained in #97), the initial `HTTP CONNECT` request never
succeeds.
This commit works around the issue by:
1. Removing hard-coded declarations of `Content-Type` and `Content-Length` headers (`request` will add them automatically if we supply `json` payload)
2. Supply the request body in the `json` parameter (as an object - not as a JSON-stringified string)
3. Remove the `parseAndRespond` function which is no longer needed, as `request` returns a JSON object (it parses it for us)
Also, lots of tests relied on the way things worked before, with the `body` parameter, the custom content headers, and our own response JSON parsing. Updated them all, and they all …
> Fix request proxy bug due to "Content-Length" header

- test/unit/senderSpec.js
Tests broke after merging 2 PRs. The `request-proxy-fix` PR modified
the `request.body` to `request.json` and the `unicast-messaging-support` relied on that property for its tests.
@hypesystem fyi
> Fix failing tests (due to request proxy fix)

- lib/sender.js
As per #145, added a check for `4xx` status code responses, which are a result of a client error.
We should not retry requests that failed due to a client error, since we’d probably be making the same mistake again in the next request(s).
> Avoid retry for 4xx HTTP status codes

- README.md
- lib/sender.js
- test/unit/senderSpec.js
Closes #186.
Returns an error to the callback in the following circumstances:
1. No valid recipient key was provided
2. A string recipient key (topic, notificationKey) was provided, but was not a string
3. An array recipient key (registrationIds, registrationTokens) was provided, but was not an array
4. A valid recipient key was provided but contained false/null/undefined/empty string
In addition:
* Added better handling for the unsent registration tokens detection, in case of a string recipient (it was not handled properly)
* Added tests to check for recipient errors
* Added tests to check for empty string recipients
* Removed a previously skipped test which has been implemented
* Listed recipient keys and types in README.md along with error-handling behavior
> Improved error handling in extractRecipient() and improved recipient documentation

- README.md
List the known issues as per #155. Currently, only 3 known unfixed
issues with `phonegap-plugin-push`.
Added today’s date as well.
> Add GCM client compatibility docs

- README.md
- lib/sender.js
- test/unit/senderSpec.js
As per https://github.com/ToothlessGear/node-gcm/issues/187#issuecomment-167965048, we decided to add a new recipient key, `to`, that accepts a registration token, pub/sub topic, or a notification key.
* Added extraction code to `extractRecipient`
* Added several tests to check for `to` key existence/behavior
* Added to recipient keys documentation in `README.md`
> Add "to" recipient key

- test/unit/senderSpec.js
As per https://github.com/ToothlessGear/node-gcm/issues/213#issuecomment-182732095, we have decided to delete this failing test as the `request` library will handle an invalid `strictSSL` parameter for us automatically.
> Remove strictSSL boolean test in senderSpec.js

- lib/sender.js
- package.json
This makes for a significantly smaller dependency tree (lodash is 2Mb, lodash.defaultsdeep is around 250kb)
> V1: Depend only on lodash.defaultsdeep (instead of all lodash)

- README.md
- lib/sender.js
- test/unit/senderSpec.js
Note: this merges into `v1`.
Simplified the way we pass recipients to the send function: now much simpler. This moves us much closer to the interface of the HTTP api, removes a lot of pretty unnecessary cruft and tests, and makes everything simpler and easier to get an overview of.
> V1: simpler recipient arg

- lib/sender.js
- test/unit/senderSpec.js
Note: this merges into v1 #238 
This refactors the sender code a whole bunch, and removes the previously exposed `sendNoRetry` method. The same effect can now be achieved with `send(msg, recipient, { retries: 0 }, callback)`.
> V1 no send no retry

- README.md
As per https://github.com/ToothlessGear/node-gcm/issues/281#issuecomment-272391870.
> Document GCM `notification` displayed in background only

- package.json
The library qs has vulnerabilities at version 6.3.1 qs is a dependency in this project through request I believe. request version ~2.81 has an updated version of qs (~6.4) without the vulnerability.
https://snyk.io/vuln/npm:qs:20170213
> fix: avoid possible prototype override protection bypass

- lib/sender.js
Closes #292.
To avoid retrying a request with an empty response, I hard-coded the `4xx` error. 
@hypesystem Please review and let me know if there’s a better way to do this in your opinion.
> Support empty JSON response from FCM

- package.json
The 'Request' package maintainers have made a breaking change in version 2.82.0+ that no longer works on Node 0.10.x or 0.12.x. Since this package still specifies a supported engine of node 0.10.0, this PR locks the 'Request' package version to 2.81.0 forever.
While the "correct" solution here may be to not use node 0.x anymore since it's been deprecated, there are some packages and configurations that will break with change made in Request.
> Lock 'Request' package to 2.81.0.

- README.md
Google announced today that by April 11, 2019, all users must have migrated off gcm to fcm. I have added a notice to the README to make it clear that we already support this migration.
Thoughts, @eladnava ?
> Notice on FCM migration deadline

- README.md
- package.json
Example of how to find the tokens which you couldn't send to.
I'm maching the two arrays together and then filtering it to get a list of tokens.
> README: Example on getting the tokens you should remove

- README.md
Failed tokens can be found with a single `filter` operation over the `registrationTokens` using the 1:1 mapping with response data. Earlier example used `map` + `filter` to achieve the same result.
> Update example to find  "bad" tokens

- README.md
- lib/message-options.js
- As per the Firebase [docs](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?authuser=0#androidfcmoptions), `fcm_options` is a new-ish parameter to allow setting a label on push notification messages. The message options does not have this as a valid config so setting it on the message will be ignored. This will allow it as a valid option.
> Add fcm_options as allowed params to message object

- lib/constants.js
- lib/sender.js
- test/unit/senderSpec.js
as per the [Firebase Error Code](https://firebase.google.com/docs/cloud-messaging/http-server-ref#error-codes) "InternalServerError" should be retired similar to "Unavailable" error.
> fix: Gcm InternalServerError should also be retied with exponential-back-off.

- package-lock.json
- package.json
Vulnerability in ajv (via request -> har-validator)
```
Upgrade request@2.87.0 to request@2.88.0 to fix
✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-AJV-584908] in ajv@5.5.2
introduced by request@2.87.0 > har-validator@5.0.3 > ajv@5.5.2
```
Several snyk vulnerabilities related to lodash@4.17.10 (fixed in @4.17.20)
```
✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-567746] in lodash@4.17.10
introduced by lodash@4.17.10
✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-LODASH-73639] in lodash@4.17.10
introduced by lodash@4.17.10
✗ Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-LODASH-590103] in lodash@4.17.10
introduced by lodash@4.17.10
✗ Prototype Pollution [High …
```
> dependency upgrades for vulnerabilities flagged by snyk

- lib/sender.js
- package-lock.json
- package.json
- test/unit/senderSpec.js
Request is deprecated, replacing with a newer library.
Tested and working.
> Replace request with axios

- lib/sender.js
Added a check for `result` property present in error, otherwise call back with error instance.
> fix: handle non-http errors correctly (#375)

- lib/sender.js
> Handle all HTTP errors correctly
