ToothlessGear/node-gcm

- package.json
> Fix engine version

- lib/sender.js
- package.json
This relates to #71, but takes a different approach (only logging to debug).
This is not a replacement for #71, but a non-breaking intermediate.
> Better debugging

- README.md
> Make it clearer how the DEBUG flag is used

- README.md
- lib/sender.js
> Default retries for `Sender#send`

- lib/sender.js
- test/unit/senderSpec.js
Fixes #93 
I am creating this PR now to get feedback (if anyone is interested). It is still missing tests and an update to the README.
> Ensure full result set

- lib/sender.js
- test/unit/senderSpec.js
> Better support for single device

- README.md
- package.json
This avoids getting test-files when installing the package
> Use `files` in package.json

- docsource/message.js.md
- docsource/sender.js.md
Initial version of documentation, made for building with [docco](http://jashkenas.github.io/docco/).
Feedback is very much welcomed.
---
Want to view a nice, rendered version of this? Get a local copy of this branch, and then build it with docco:
```js
npm install docco -g
docco docsource/*.js.md
```
The resulting files with be placed in docs/, and are viewable with your web browser.
---
This PR was originally #105, but I somehow messed it up. Oops.
> Full api docs

- README.md
- examples/notification.js
- lib/constants.js
- lib/message.js
- lib/sender.js
- test/unit/messageSpec.js
Add a message function to setup notification information.
message.addNotification('Title', 'logo path', 'Text');
> Add notification info to display on lock screen

- package.json
As mentioned in https://github.com/ToothlessGear/node-gcm/pull/116#issuecomment-94290354
@hypesystem This works fine on Windows 8.1
http://imgur.com/HjRtk0M
BTW, have you thought about adding a Travis build? Free for FOSS :smile:
> Normalize test execution

- CONTRIBUTING.md
- VERSIONING.md
Rewrote CONTRIBUTING.md to clear up common causes of misunderstandings.
> Contributing

- lib/sender.js
- package.json
- test/unit/senderSpec.js
Hello,
I have added a field in the "options" object to set "strictSsl" to false. This comes in handy when behind a corporate firewall with an invalid certificate. :)
Hope you find this useful and gets integrated in the project!
Regards,
Marc
> Add capability to set strictSSL.

- package.json
- test/unit/senderSpec.js
I got confused when I read the line as it was my first time working with node js tests.
> fixing indentation in a line inside senderSpec

- CONTRIBUTING.md
- README.md
I wanted to add a few features, I was struggling to find how to get started with writing code and run the tests, so I created this pull request. Please suggest more things which can help in getting started quickly.
> adding dependencies installation & test run info in contributing

- lib/constants.js
- lib/sender.js
- package.json
> Migrate from GCM to FCM

- lib/constants.js
- lib/multicastresult.js
- lib/result.js
**Note: this merges into `refactor--spring-cleaning` (#234)**
Bits of refactoring/deprecation notices for concepts we are not using.
> Refactor/spring cleaning: other

- lib/message.js
**Note: this merges into `refactor--spring-cleaning` (#234)**
Bits of refactoring for Message.js. All tests are intact :smile:
> Refactor/spring cleaning: Message.js

- README.md
> Add --save argument to `npm install node-gcm` in README

- CHANGELOG.md
- README.md
- lib/sender.js
- package.json
- test/unit/senderSpec.js
Aimed to solve this issue: https://github.com/ToothlessGear/node-gcm/issues/261
> Support for multiple topics using condition parameter of FCM send API

- package.json
Here is the [changelog](https://github.com/visionmedia/debug/blob/master/History.md).
> Upgrade debug

- README.md
> Improve example usage docs (more detailed comments)

- lib/sender.js
> Warn when sending a message with data.from in its payload

- lib/sender.js
The commit which broke tests:
https://github.com/ToothlessGear/node-gcm/commit/41005018a86da3b656d433527e2a6770cd5965ee
@hypesystem Please review.
> Fix broken tests from commit 4100501

- lib/message-options.js
- test/unit/messageSpec.js
FCM added the mutable_content field to API
see https://github.com/firebase/quickstart-ios/issues/70 for more detail
> Support for ios mutable-content

- package.json
> Update debug dependency due to RegEx DoS vulnerability

- README.md
> Document GCM message options in README

- lib/sender.js
> Pass on recipient FCM param name from extractRecipient

- package-lock.json
- package.json
the dependency `request` had a security issue in one of its dependencies lately.
decided to bump to the latest version: 2.8.7.0
before i changed anything:
```                                                                                
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Out-of-bounds Read                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ stringstream                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ request                                                      │ …
```
> versionbumped dependency 'request'

- README.md
> adds mutableContent doku entry

- lib/sender.js
- package.json
- test/unit/senderSpec.js
> Allow uri override

- .github/workflows/ci.yml
> ci: add CI tests

- .github/workflows/ci.yml
Improve workflow job names; remove tests for node versions that are out of LTS
> ci: improve node job names

- README.md
> README: Update instructions on obtaining FCM Server Key

- package-lock.json
Restore existing versions cached in `package-lock.json` before #372 to avoid breaking anything.
> Restore old dependency versions in package-lock.json
